version: "3.9"

networks:
  webservices_project_iot-network:
    driver: bridge
  webservices_project_healthtrack-network:
    driver: bridge
  webservices_project_spring-network:
    driver: bridge
  webservices_project_frontend-network:
    driver: bridge

volumes:
  postgres_device_data:
  influxdb_data:
  mongodb_data:
  sqlserver_data:
  postgres_suivipatients_data:

services:
  # --- IoT Device App ---
  device_service:
    build: ./device
    container_name: device_service
    ports:
      - "8000:8000"
    depends_on:
      - device_db
      - influxdb
    environment:
      DATABASE_URL: postgresql://device_user:device_pass@device_db:5432/device_db
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: my-token
      INFLUX_ORG: my-org
      INFLUX_BUCKET: iot_data
    networks:
      - webservices_project_iot-network

  device_db:
    image: postgres:15
    container_name: device_db
    restart: always
    environment:
      POSTGRES_USER: device_user
      POSTGRES_PASSWORD: device_pass
      POSTGRES_DB: device_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_device_data:/var/lib/postgresql/data
    networks:
      - webservices_project_iot-network

  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: iot_data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - webservices_project_iot-network

  # --- Profile ---
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: healthtrack
    volumes:
      - mongodb_data:/data/db
    networks:
      - webservices_project_healthtrack-network

  profile_service:
    build: ./profile
    container_name: profile_service
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongodb:27017/healthtrack
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
    depends_on:
      - mongodb
    networks:
      - webservices_project_healthtrack-network
    volumes:
      - ./profile/src:/app/src
    command: npm run dev

  # --- Spring Boot with SQL Server ---
  db_sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P@ssw0rd1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - webservices_project_spring-network

  planification_service:
    build: ./planification
    ports:
      - "8082:8080"
    depends_on:
      - db_sql
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db_sql:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    command: sh -c "sleep 120 && java -jar app.jar"
    restart: unless-stopped
    networks:
      - webservices_project_spring-network

  # --- Spring Boot Suivi Patients ---
  postgres_suivipatients:
    image: postgres:17
    container_name: postgres_suivipatients
    restart: always
    environment:
      POSTGRES_DB: suivipatients
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5434:5432"
    volumes:
      - postgres_suivipatients_data:/var/lib/postgresql/data
    networks:
      - webservices_project_spring-network

  suivipatients_service:
    build: ./suivitraitement
    container_name: suivipatients_service
    depends_on:
      - postgres_suivipatients
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_suivipatients:5432/suivi_traitement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8002
    ports:
      - "8002:8002"
    restart: always
    networks:
      - webservices_project_spring-network

  # --- Frontend Nextjs ---
  frontend_service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    networks:
      - webservices_project_frontend-network
