version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: 1234
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  app:
    image: planification-module:latest
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=planification_db;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  sqlserver-data: