spring.application.name=planification
# Datasource SQL Server
spring.datasource.url=jdbc:sqlserver://DESKTOP-DSCNNK3:1433;databaseName=planification_db;encrypt=true;trustServerCertificate=true;createDatabaseIfNotExist=true
spring.datasource.username=BR
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true


server.port=8082