# src/main/resources/application.properties

# Connexion à master
spring.datasource.url=jdbc:sqlserver://db:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd1234

# Hibernate crée la base + tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# spring.sql.init.mode=always
# spring.sql.init.schema-locations=classpath:schema.sql