spring.application.name=Suivi-Patients
# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/suivi_traitement
spring.datasource.username=postgres
spring.datasource.password=admin1234
server.port=8002
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5000,http://localhost:8080,http://localhost:3000}

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
]